nodejs:
  replicaCount: 1
  nameOverride: staging-4pl-route-optimization-pre-process
  imagePullSecrets:
    name: telregistry
  image:
    repository: registry.dev.true-e-logistics.com/sendit/4pl-route-optimization-pre-process
    pullPolicy: Always
  containerPorts:
    - 80
  env:
    - name: APP_NAME
      value: 4pl-route-optimization-pre-process
    - name: NODE_ENV
      value: staging
    - name: KOA_PORT
      value: '80'
    - name: KOA_NAMESPACE
      value: 8242dcf9-78a7-479d-8172-7ff3f8bfa952
    - name: OPTIMIZATION_HOST
      value: https://kong-api.staging.sendit.asia
    - name: OMS_URL
      value: https://api.staging.sendit.asia/4pl/oms
    - name: ADDRESS_SERVICE_URL
      value: https://api.staging.sendit.asia/4pl/address
    - name: ADDRESS_TYPE_ID
      value: 5e36aa2284252389d7bd110f
  workingDir: /var/source
  healthCheck:
    httpGet:
      path: /system/health
      port: 80
  type: ClusterIP
  default:
    ports:
      - name: staging-4pl-route-optimization-pre-process
        externalPort: 80
        internalPort: 80
        protocol: TCP
